wiki_links:
	latex wiki_links 
	bibtex wiki_links
	latex wiki_links
	latex wiki_links
	dvipdf wiki_links
clean:
	rm -f *.aux *.log *.nav *.out *.snm *.toc *.vrb *.idx *~ *.lot *.lof *.blg *.bbl *.dvi *.pdf

.force:
