article:
	latex rlc09hat
	bibtex rlc09hat
	latex rlc09hat
	latex rlc09hat
	dvipdf rlc09hat

pdf:
	pdflatex rlc09hat
	bibtex rlc09hat
	pdflatex rlc09hat
	pdflatex rlc09hat

clean:
	rm -f *.aux *.log *.nav *.out *.snm *.toc *.vrb *.idx *~ *.lot *.lof *.blg *.bbl *.dvi *.pdf

.force:
