thesis:
	latex thesis
	bibtex thesis
	latex thesis
	latex thesis
	dvipdf thesis

pdf:
	pdflatex thesis
	bibtex thesis
	pdflatex thesis
	pdflatex thesis

chapter:
	latex chapter
	bibtex chapter
	latex chapter
	dvipdfm chapter
clean:
	rm -f *.aux *.log *.nav *.out *.snm *.toc *.vrb *.idx *~ *.lot *.lof *.blg *.bbl *.dvi *.pdf

.force:
